language: python
sudo: false
python:
  - 2.7
  - 3.4
  - pypy
  - pypy3
install:
  - pip install --user -U pip setuptools codecov
  - python setup.py -q install
script: make coverage
after_success:
  - codecov