language: python
cache: pip
sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=8baf5900b3c0520c3a1e3d627d0de5ca1446555def139e1972e8c32d49278c94
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - pip install -U pip six setuptools codecov
  - python setup.py install
script: make coverage
after_success:
  - codecov
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
